### ISSUE TITLE
Merhabalar.

### ISSUE THREAD

**Issue by rifatozkancomtr** [AlperShal/Dolap-Scrapper#1]
Merhaba dolap üzerinden xml ürün ekleme ve stok yükleme yapabilen bir bot yazılabilir mi?

**Comment by AlperShal** [comment]
Merhaba,

Web arayüzünde yükleme yapılabilecek herhangi bir arayüz yok sanırım. Alternatif olarak mobil cihazınızdan bir tane yükleme yapıp onun paket trafiğini kopyalayıp bilgisayar üzerinden diğer listelemeler için XML'den çektiğiniz verileri kullanarak paketi manipüle edip yeni listelemeler oluşturabilirsiniz ama çok kolay olmayacaktır.

**Comment by rifatozkancomtr** [comment]
> Merhaba,
> 
> Web arayüzünde yükleme yapılabilecek herhangi bir arayüz yok sanırım. Alternatif olarak mobil cihazınızdan bir tane yükleme yapıp onun paket trafiğini kopyalayıp bilgisayar üzerinden diğer listelemeler için XML'den çektiğiniz verileri kullanarak paketi manipüle edip yeni listelemeler oluşturabilirsiniz ama çok kolay olmayacaktır.

Tahmini olarak bu işlemi yapabilecek bir botun maliyeti ne olur peki?

**Comment by AlperShal** [comment]
Piyasayı hiç bilmiyorum maalesef bu konuda bir şey diyemeyeceğim.

**Comment by rifatozkancomtr** [comment]
Pardon geç gördum siz bir fiyat veremez misiniz? 
Yani siz yapsanız.

**Comment by AlperShal** [comment]
> Pardon geç gördum siz bir fiyat veremez misiniz? 
> Yani siz yapsanız.

Maalesef hiç vaktim yok bu aralar.

**Comment by rifatozkancomtr** [comment]
Teşekkürler zaman ayırdığınız için yinede iyi akşamlar.
